const WIKI_ITEMS = {
    // --- Custom Mod Items (Artifacts & Crafting) ---
    "timemercenaries:dimensional_time_clock": { name: "Dimensional Time Clock", image: "images/items/dimensional_time_clock.png" },
    "timemercenaries:timecrystal": { name: "Timecrystal", image: "images/items/timecrystal.png" },
    "timemercenaries:green_timecrystal": { name: "Green Timecrystal", image: "images/items/green_timecrystal.png" },
    "timemercenaries:blue_timecrystal": { name: "Blue Timecrystal", image: "images/items/blue_timecrystal.png" },
    "timemercenaries:red_timecrystal": { name: "Red Timecrystal", image: "images/items/red_timecrystal.png" },
    "timemercenaries:broken_module": { name: "Broken Module", image: "images/items/broken_module.png" },
    "timemercenaries:broken_green_module": { name: "Broken Green Module", image: "images/items/broken_green_module.png" },
    "timemercenaries:broken_blue_module": { name: "Broken Blue Module", image: "images/items/broken_blue_module.png" },
    "timemercenaries:broken_red_module": { name: "Broken Red Module", image: "images/items/broken_red_module.png" },
    "timemercenaries:void_woven_greaves": { name: "Void-Woven Greaves", image: "images/items/void_woven_greaves.png" },
    "timemercenaries:gilded_grudge": { name: "The Gilded Grudge", image: "images/items/gilded_grudge.png" },
    "timemercenaries:ocean_soul": { name: "Ocean Soul", image: "images/items/ocean_soul.png" },
    "timemercenaries:primordial_growth_moss": { name: "Primordial Growth Moss", image: "images/items/primordial_growth_moss.png" },
    "timemercenaries:delirium_concoction": { name: "Grizzle's Delirium Concoction", image: "images/items/delirium_concoction.png" },
    "timemercenaries:walking_stick": { name: "Nomad's Walking Stick", image: "images/items/walking_stick.png" },
    "timemercenaries:primal_hunting_spear": { name: "Primal Hunting Spear", image: "images/items/primal_hunting_spear.png" },
    "timemercenaries:sword_of_chickening": { name: "Sword of Chickening", image: "images/items/sword_of_chickening.png" },
    "timemercenaries:constellar_staff": { name: "Constellar Staff", image: "images/items/constellar_staff.png" },
    "timemercenaries:thunder_in_a_bottle": { name: "Thunder in a Bottle", image: "images/items/thunder_in_a_bottle.png" },
    "timemercenaries:rainbow_timecrystal": { name: "Rainbow Timecrystal", image: "images/items/rainbow_timecrystal.png" },
    "timemercenaries:chains_of_supremacy": { name: "Chains of Supremacy", image: "images/items/chains_of_supremacy.png" },
    "timemercenaries:cap_of_commerce": { name: "Cap of Commerce", image: "images/items/cap_of_commerce.png" },
    "timemercenaries:heart_of_the_mountain": { name: "Heart of the Mountain", image: "images/items/heart_of_the_mountain.png" },
    "timemercenaries:void_woven_leggings": { name: "Void-Woven Leggings", image: "images/items/void_woven_leggings.png" },
    "timemercenaries:talisman_of_the_wilds": { name: "Talisman of the Wilds", image: "images/items/talisman_of_the_wilds.png" },
    "timemercenaries:helm_of_the_first_explorer": { name: "Helm of the First Explorer", image: "images/items/helm_of_the_first_explorer.png" },
    "timemercenaries:hydro_gem_of_evergrowth": { name: "Hydro-Gem of Evergrowth", image: "images/items/hydro_gem_of_evergrowth.png" },
    "timemercenaries:brutes_war_horn": { name: "Brute's War Horn", image: "images/items/brutes_war_horn.png" },
    "timemercenaries:volatile_concoction_casing": { name: "Volatile Concoction Casing", image: "images/items/volatile_concoction_casing.png" },
    "timemercenaries:tome_of_synthesis": { name: "Tome of Synthesis", image: "images/items/tome_of_synthesis.png" },
    "timemercenaries:guild_bearers_seal": { name: "Guild-Bearer's Seal", image: "images/items/guild_bearers_seal.png" },
    "timemercenaries:transmuters_gizzard": { name: "Transmuter's Gizzard", image: "images/items/transmuters_gizzard.png" },
    "timemercenaries:rift_in_a_bottle": { name: "Rift in a Bottle", image: "images/items/rift_in_a_bottle.png" },
    "timemercenaries:dice_of_infinite_possibilities": { name: "Dice of Infinite Possibilities", image: "images/items/dice_of_infinite_possibilities.png" },
    "timemercenaries:everfull_feedbag": { name: "Ever-full Feedbag", image: "images/items/everfull_feedbag.png" },

    // --- Common Vanilla Items ---
    "minecraft:cobblestone": { name: "Cobblestone", image: "images/items/cobblestone.png" },
    "minecraft:dirt": { name: "Dirt", image: "images/items/dirt.png" },
    "minecraft:sand": { name: "Sand", image: "images/items/sand.png" },
    "minecraft:stone": { name: "Stone", image: "images/items/stone.png" },
    "minecraft:diorite": { name: "Diorite", image: "images/items/diorite.png" },
    "minecraft:granite": { name: "Granite", image: "images/items/granite.png" },
    "minecraft:andesite": { name: "Andesite", image: "images/items/andesite.png" },
    "minecraft:netherrack": { name: "Netherrack", image: "images/items/netherrack.png" },
    "minecraft:soul_sand": { name: "Soul Sand", image: "images/items/soul_sand.png" },
    "minecraft:soul_soil": { name: "Soul Soil", image: "images/items/soul_soil.png" },
    "minecraft:basalt": { name: "Basalt", image: "images/items/basalt.png" },
    "minecraft:blackstone": { name: "Blackstone", image: "images/items/blackstone.png" },
    "minecraft:end_stone": { name: "End Stone", image: "images/items/end_stone.png" },
    "minecraft:end_stone_bricks": { name: "End Stone Bricks", image: "images/items/end_stone_bricks.png" },
    "minecraft:purpur_block": { name: "Purpur Block", image: "images/items/purpur_block.png" },
    "minecraft:coal": { name: "Coal", image: "images/items/coal.png" },
    "minecraft:stick": { name: "Stick", image: "images/items/stick.png" },
    "minecraft:string": { name: "String", image: "images/items/string.png" },
    "minecraft:feather": { name: "Feather", image: "images/items/feather.png" },
    "minecraft:gunpowder": { name: "Gunpowder", image: "images/items/gunpowder.png" },
    "minecraft:bone": { name: "Bone", image: "images/items/bone.png" },
    "minecraft:rotten_flesh": { name: "Rotten Flesh", image: "images/items/rotten_flesh.png" },
    "minecraft:spider_eye": { name: "Spider Eye", image: "images/items/spider_eye.png" },
    "minecraft:glass_bottle": { name: "Glass Bottle", image: "images/items/glass_bottle.png" },
    "minecraft:arrow": { name: "Arrow", image: "images/items/arrow.png" },
    "minecraft:torch": { name: "Torch", image: "images/items/torch.png" },
    "minecraft:clay": { name: "Clay", image: "images/items/clay.png" },
    "minecraft:snowball": { name: "Snowball", image: "images/items/snowball.png" },
    "minecraft:cooked_cod": { name: "Cooked Cod", image: "images/items/cooked_cod.png" },
    "minecraft:cooked_salmon": { name: "Cooked Salmon", image: "images/items/cooked_salmon.png" },
    "minecraft:wheat_seeds": { name: "Wheat Seeds", image: "images/items/wheat_seeds.png" },
    "minecraft:melon_seeds": { name: "Melon Seeds", image: "images/items/melon_seeds.png" },
    "minecraft:pumpkin_seeds": { name: "Pumpkin Seeds", image: "images/items/pumpkin_seeds.png" },
    "minecraft:beetroot_seeds": { name: "Beetroot Seeds", image: "images/items/beetroot_seeds.png" },
    "minecraft:wooden_sword": { name: "Wooden Sword", image: "images/items/wooden_sword.png" },
    "minecraft:wooden_pickaxe": { name: "Wooden Pickaxe", image: "images/items/wooden_pickaxe.png" },
    "minecraft:wooden_axe": { name: "Wooden Axe", image: "images/items/wooden_axe.png" },
    "minecraft:wooden_shovel": { name: "Wooden Shovel", image: "images/items/wooden_shovel.png" },
    "minecraft:wooden_hoe": { name: "Wooden Hoe", image: "images/items/wooden_hoe.png" },
    "minecraft:stone_sword": { name: "Stone Sword", image: "images/items/stone_sword.png" },
    "minecraft:stone_pickaxe": { name: "Stone Pickaxe", image: "images/items/stone_pickaxe.png" },
    "minecraft:stone_axe": { name: "Stone Axe", image: "images/items/stone_axe.png" },
    "minecraft:stone_shovel": { name: "Stone Shovel", image: "images/items/stone_shovel.png" },
    "minecraft:stone_hoe": { name: "Stone Hoe", image: "images/items/stone_hoe.png" },
    "minecraft:poppy": { name: "Poppy", image: "images/items/poppy.png" },
    "minecraft:dandelion": { name: "Dandelion", image: "images/items/dandelion.png" },
    "minecraft:red_tulip": { name: "Red Tulip", image: "images/items/red_tulip.png" },
    "minecraft:orange_tulip": { name: "Orange Tulip", image: "images/items/orange_tulip.png" },
    "minecraft:white_tulip": { name: "White Tulip", image: "images/items/white_tulip.png" },
    "minecraft:pink_tulip": { name: "Pink Tulip", image: "images/items/pink_tulip.png" },
    "minecraft:red_mushroom": { name: "Red Mushroom", image: "images/items/red_mushroom.png" },
    "minecraft:brown_mushroom": { name: "Brown Mushroom", image: "images/items/brown_mushroom.png" },
    "minecraft:sugar_cane": { name: "Sugar Cane", image: "images/items/sugar_cane.png" },
    "minecraft:kelp": { name: "Kelp", image: "images/items/kelp.png" },
    "minecraft:seagrass": { name: "Seagrass", image: "images/items/seagrass.png" },
    "minecraft:sea_pickle": { name: "Sea Pickle", image: "images/items/sea_pickle.png" },
    "minecraft:grass": { name: "Grass", image: "images/items/grass.png" },
    "minecraft:potion": { name: "Potion", image: "images/items/potion.png" },
    "minecraft:splash_potion": { name: "Splash Potion", image: "images/items/splash_potion.png" },

    // --- Uncommon Vanilla Items ---
    "minecraft:iron_ingot": { name: "Iron Ingot", image: "images/items/iron_ingot.png" },
    "minecraft:gold_ingot": { name: "Gold Ingot", image: "images/items/gold_ingot.png" },
    "minecraft:raw_iron": { name: "Raw Iron", image: "images/items/raw_iron.png" },
    "minecraft:raw_copper": { name: "Raw Copper", image: "images/items/raw_copper.png" },
    "minecraft:raw_gold": { name: "Raw Gold", image: "images/items/raw_gold.png" },
    "minecraft:magma_cream": { name: "Magma Cream", image: "images/items/magma_cream.png" },
    "minecraft:slime_ball": { name: "Slimeball", image: "images/items/slime_ball.png" },
    "minecraft:nether_wart": { name: "Nether Wart", image: "images/items/nether_wart.png" },
    "minecraft:magma_block": { name: "Magma Block", image: "images/items/magma_block.png" },
    "minecraft:crimson_nylium": { name: "Crimson Nylium", image: "images/items/crimson_nylium.png" },
    "minecraft:warped_nylium": { name: "Warped Nylium", image: "images/items/warped_nylium.png" },
    "minecraft:obsidian": { name: "Obsidian", image: "images/items/obsidian.png" },
    "minecraft:sandstone": { name: "Sandstone", image: "images/items/sandstone.png" },
    "minecraft:terracotta": { name: "Terracotta", image: "images/items/terracotta.png" },
    "minecraft:experience_bottle": { name: "Bottle o' Enchanting", image: "images/items/experience_bottle.png" },
    "minecraft:firework_rocket": { name: "Firework Rocket", image: "images/items/firework_rocket.png" },
    "minecraft:leather": { name: "Leather", image: "images/items/leather.png" },
    "minecraft:cooked_beef": { name: "Steak", image: "images/items/cooked_beef.png" },
    "minecraft:cooked_chicken": { name: "Cooked Chicken", image: "images/items/cooked_chicken.png" },
    "minecraft:cooked_mutton": { name: "Cooked Mutton", image: "images/items/cooked_mutton.png" },
    "minecraft:cooked_porkchop": { name: "Cooked Porkchop", image: "images/items/cooked_porkchop.png" },
    "minecraft:cooked_rabbit": { name: "Cooked Rabbit", image: "images/items/cooked_rabbit.png" },
    "minecraft:enchanted_book": { name: "Enchanted Book", image: "images/items/enchanted_book.png" },
    "minecraft:allium": { name: "Allium", image: "images/items/allium.png" },
    "minecraft:azure_bluet": { name: "Azure Bluet", image: "images/items/azure_bluet.png" },
    "minecraft:blue_orchid": { name: "Blue Orchid", image: "images/items/blue_orchid.png" },
    "minecraft:cornflower": { name: "Cornflower", image: "images/items/cornflower.png" },
    "minecraft:oxeye_daisy": { name: "Oxeye Daisy", image: "images/items/oxeye_daisy.png" },
    "minecraft:dead_bush": { name: "Dead Bush", image: "images/items/dead_bush.png" },
    "minecraft:fern": { name: "Fern", image: "images/items/fern.png" },
    "minecraft:brain_coral": { name: "Brain Coral", image: "images/items/brain_coral.png" },
    "minecraft:bubble_coral": { name: "Bubble Coral", image: "images/items/bubble_coral.png" },
    "minecraft:fire_coral": { name: "Fire Coral", image: "images/items/fire_coral.png" },
    "minecraft:horn_coral": { name: "Horn Coral", image: "images/items/horn_coral.png" },
    "minecraft:tube_coral": { name: "Tube Coral", image: "images/items/tube_coral.png" },
    "minecraft:dead_brain_coral": { name: "Dead Brain Coral", image: "images/items/dead_brain_coral.png" },
    "minecraft:dead_bubble_coral": { name: "Dead Bubble Coral", image: "images/items/dead_bubble_coral.png" },
    "minecraft:dead_fire_coral": { name: "Dead Fire Coral", image: "images/items/dead_fire_coral.png" },
    "minecraft:dead_horn_coral": { name: "Dead Horn Coral", image: "images/items/dead_horn_coral.png" },
    "minecraft:dead_tube_coral": { name: "Dead Tube Coral", image: "images/items/dead_tube_coral.png" },
    "minecraft:candle": { name: "Candle", image: "images/items/candle.png" },
    "minecraft:egg": { name: "Egg", image: "images/items/egg.png" },
    "minecraft:shield": { name: "Shield", image: "images/items/shield.png" },
    "minecraft:spectral_arrow": { name: "Spectral Arrow", image: "images/items/spectral_arrow.png" },
    "minecraft:lava_bucket": { name: "Lava Bucket", image: "images/items/lava_bucket.png" },
    "minecraft:piston": { name: "Piston", image: "images/items/piston.png" },

    // --- Rare Vanilla Items ---
    "minecraft:diamond": { name: "Diamond", image: "images/items/diamond.png" },
    "minecraft:lapis_lazuli": { name: "Lapis Lazuli", image: "images/items/lapis_lazuli.png" },
    "minecraft:iron_ore": { name: "Iron Ore", image: "images/items/iron_ore.png" },
    "minecraft:copper_ore": { name: "Copper Ore", image: "images/items/copper_ore.png" },
    "minecraft:gold_ore": { name: "Gold Ore", image: "images/items/gold_ore.png" },
    "minecraft:redstone": { name: "Redstone", image: "images/items/redstone.png" },
    "minecraft:blaze_rod": { name: "Blaze Rod", image: "images/items/blaze_rod.png" },
    "minecraft:crying_obsidian": { name: "Crying Obsidian", image: "images/items/crying_obsidian.png" },
    "minecraft:lily_of_the_valley": { name: "Lily of the Valley", image: "images/items/lily_of_the_valley.png" },
    "minecraft:sunflower": { name: "Sunflower", image: "images/items/sunflower.png" },
    "minecraft:bamboo": { name: "Bamboo", image: "images/items/bamboo.png" },
    "minecraft:vine": { name: "Vines", image: "images/items/vine.png" },
    "minecraft:armor_stand": { name: "Armor Stand", image: "images/items/armor_stand.png" },
    "minecraft:creeper_head": { name: "Creeper Head", image: "images/items/creeper_head.png" },
    "minecraft:crossbow": { name: "Crossbow", image: "images/items/crossbow.png" },
    "minecraft:piglin_head": { name: "Piglin Head", image: "images/items/piglin_head.png" },
    "minecraft:skeleton_skull": { name: "Skeleton Skull", image: "images/items/skeleton_skull.png" },
    "minecraft:zombie_head": { name: "Zombie Head", image: "images/items/zombie_head.png" },
    "minecraft:cod_bucket": { name: "Bucket of Cod", image: "images/items/cod_bucket.png" },
    "minecraft:salmon_bucket": { name: "Bucket of Salmon", image: "images/items/salmon_bucket.png" },
    "minecraft:tropical_fish_bucket": { name: "Bucket of Tropical Fish", image: "images/items/tropical_fish_bucket.png" },
    "minecraft:lily_pad": { name: "Lily Pad", image: "images/items/lily_pad.png" },
    "minecraft:sponge": { name: "Sponge", image: "images/items/sponge.png" },
    "minecraft:mud": { name: "Mud", image: "images/items/mud.png" },
    "minecraft:cobbled_deepslate": { name: "Cobbled Deepslate", image: "images/items/cobbled_deepslate.png" },
    "minecraft:rabbit_hide": { name: "Rabbit Hide", image: "images/items/rabbit_hide.png" },
    "minecraft:sweet_berries": { name: "Sweet Berries", image: "images/items/sweet_berries.png" },
    "minecraft:golden_sword": { name: "Golden Sword", image: "images/items/golden_sword.png" },
    "minecraft:golden_axe": { name: "Golden Axe", image: "images/items/golden_axe.png" },
    "minecraft:golden_helmet": { name: "Golden Helmet", image: "images/items/golden_helmet.png" },
    "minecraft:golden_chestplate": { name: "Golden Chestplate", image: "images/items/golden_chestplate.png" },
    "minecraft:golden_leggings": { name: "Golden Leggings", image: "images/items/golden_leggings.png" },
    "minecraft:golden_boots": { name: "Golden Boots", image: "images/items/golden_boots.png" },

    // --- Epic Vanilla Items ---
    "minecraft:netherite_scrap": { name: "Netherite Scrap", image: "images/items/netherite_scrap.png" },
    "minecraft:shulker_shell": { name: "Shulker Shell", image: "images/items/shulker_shell.png" },
    "minecraft:amethyst_shard": { name: "Amethyst Shard", image: "images/items/amethyst_shard.png" },
    "minecraft:emerald": { name: "Emerald", image: "images/items/emerald.png" },
    "minecraft:lapis_ore": { name: "Lapis Lazuli Ore", image: "images/items/lapis_ore.png" },
    "minecraft:redstone_ore": { name: "Redstone Ore", image: "images/items/redstone_ore.png" },
    "minecraft:echo_shard": { name: "Echo Shard", image: "images/items/echo_shard.png" },
    "minecraft:sculk_sensor": { name: "Sculk Sensor", image: "images/items/sculk_sensor.png" },
    "minecraft:ghast_tear": { name: "Ghast Tear", image: "images/items/ghast_tear.png" },
    "minecraft:wither_skeleton_skull": { name: "Wither Skeleton Skull", image: "images/items/wither_skeleton_skull.png" },
    "minecraft:bell": { name: "Bell", image: "images/items/bell.png" },
    "minecraft:grass_block": { name: "Grass Block", image: "images/items/grass_block.png" },
    "minecraft:mycelium": { name: "Mycelium", image: "images/items/mycelium.png" },
    "minecraft:podzol": { name: "Podzol", image: "images/items/podzol.png" },
    "minecraft:torchflower": { name: "Torchflower", image: "images/items/torchflower.png" },
    "minecraft:dragon_breath": { name: "Dragon's Breath", image: "images/items/dragon_breath.png" },
    "minecraft:end_crystal": { name: "End Crystal", image: "images/items/end_crystal.png" },
    "minecraft:shulker_box": { name: "Shulker Box", image: "images/items/shulker_box.png" },
    "minecraft:rabbit_foot": { name: "Rabbit's Foot", image: "images/items/rabbit_foot.png" },
    "minecraft:scute": { name: "Scute", image: "images/items/scute.png" },
    "minecraft:nautilus_shell": { name: "Nautilus Shell", image: "images/items/nautilus_shell.png" },
    "minecraft:prismarine_crystals": { name: "Prismarine Crystals", image: "images/items/prismarine_crystals.png" },
    "minecraft:prismarine_shard": { name: "Prismarine Shard", image: "images/items/prismarine_shard.png" },
    "minecraft:trident": { name: "Trident", image: "images/items/trident.png" },
    "minecraft:pufferfish_bucket": { name: "Bucket of Pufferfish", image: "images/items/pufferfish_bucket.png" },
    "minecraft:calcite": { name: "Calcite", image: "images/items/calcite.png" },
    "minecraft:deepslate": { name: "Deepslate", image: "images/items/deepslate.png" },
    "minecraft:prismarine": { name: "Prismarine", image: "images/items/prismarine.png" },
    "minecraft:tuff": { name: "Tuff", image: "images/items/tuff.png" },
    "minecraft:sniffer_egg": { name: "Sniffer Egg", image: "images/items/sniffer_egg.png" },
    "minecraft:turtle_egg": { name: "Turtle Egg", image: "images/items/turtle_egg.png" },
    
    // --- Legendary Vanilla Items ---
    "minecraft:amethyst_cluster": { name: "Amethyst Cluster", image: "images/items/amethyst_cluster.png" },
    "minecraft:diamond_ore": { name: "Diamond Ore", image: "images/items/diamond_ore.png" },
    "minecraft:emerald_ore": { name: "Emerald Ore", image: "images/items/emerald_ore.png" },
    "minecraft:sculk_shrieker": { name: "Sculk Shrieker", image: "images/items/sculk_shrieker.png" },
    "minecraft:dragon_egg": { name: "Dragon Egg", image: "images/items/dragon_egg.png" },
    "minecraft:dragon_head": { name: "Dragon Head", image: "images/items/dragon_head.png" },
    "minecraft:player_head": { name: "Player Head", image: "images/items/player_head.png" },
    "minecraft:heart_of_the_sea": { name: "Heart of the Sea", image: "images/items/heart_of_the_sea.png" },
    "minecraft:elytra": { name: "Elytra", image: "images/items/elytra.png" },
    "minecraft:name_tag": { name: "Name Tag", image: "images/items/name_tag.png" },
    "minecraft:netherite_upgrade_smithing_template": { name: "Netherite Upgrade", image: "images/items/netherite_upgrade_smithing_template.png" },
    "minecraft:nether_star": { name: "Nether Star", image: "images/items/nether_star.png" },
    "minecraft:wither_rose": { name: "Wither Rose", image: "images/items/wither_rose.png" },
    "minecraft:totem_of_undying": { name: "Totem of Undying", image: "images/items/totem_of_undying.png" },
    "minecraft:netherite_block": { name: "Block of Netherite", image: "images/items/netherite_block.png" },
    "minecraft:diamond_block": { name: "Block of Diamond", image: "images/items/diamond_block.png" },
    "minecraft:enchanted_golden_apple": { name: "Enchanted Golden Apple", image: "images/items/enchanted_golden_apple.png" },
    "minecraft:suspicious_stew": { name: "Suspicious Stew", image: "images/items/suspicious_stew.png" },
    "minecraft:lodestone": { name: "Lodestone", image: "images/items/lodestone.png" },
    "minecraft:ender_chest": { name: "Ender Chest", image: "images/items/ender_chest.png" },
    "minecraft:observer": { name: "Observer", image: "images/items/observer.png" },
    "minecraft:dispenser": { name: "Dispenser", image: "images/items/dispenser.png" },
    "minecraft:jukebox": { name: "Jukebox", image: "images/items/jukebox.png" },
    "minecraft:lightning_rod": { name: "Lightning Rod", image: "images/items/lightning_rod.png" },
    "minecraft:lava_bucket": { name: "Lava Bucket", image: "images/items/lava_bucket.png" },
    "minecraft:fermented_spider_eye": { name: "Fermented Spider Eye", image: "images/items/fermented_spider_eye.png" },
    "minecraft:slime_block": { name: "Slime Block", image: "images/items/slime_block.png" },
    "minecraft:recovery_compass": { name: "Recovery Compass", image: "images/items/recovery_compass.png" },
    "minecraft:explorer_pottery_sherd": { name: "Explorer Pottery Sherd", image: "images/items/explorer_pottery_sherd.png" },
    "minecraft:spyglass": { name: "Spyglass", image: "images/items/spyglass.png" },
    "minecraft:diamond_hoe": { name: "Diamond Hoe", image: "images/items/diamond_hoe.png" },
    "minecraft:hay_block": { name: "Hay Bale", image: "images/items/hay_block.png" },
    "minecraft:spore_blossom": { name: "Spore Blossom", image: "images/items/spore_blossom.png" },
    "minecraft:moss_block": { name: "Moss Block", image: "images/items/moss_block.png" },
    "minecraft:sand": { name: "Sand", image: "images/items/sand.png" },
    "minecraft:sponge": { name: "Sponge", image: "images/items/sponge.png" },
    "minecraft:dead_bush": { name: "Dead Bush", image: "images/items/dead_bush.png" },
    "minecraft:enchanting_table": { name: "Enchanting Table", image: "images/items/enchanting_table.png" },
    "minecraft:book": { name: "Book", image: "images/items/book.png" },
    "minecraft:amethyst_block": { name: "Block of Amethyst", image: "images/items/amethyst_block.png" },
    "minecraft:redstone_block": { name: "Block of Redstone", image: "images/items/redstone_block.png" },
    "minecraft:emerald_block": { name: "Block of Emerald", image: "images/items/emerald_block.png" },
    "minecraft:netherite_axe": { name: "Netherite Axe", image: "images/items/netherite_axe.png" },
    "minecraft:gilded_blackstone": { name: "Gilded Blackstone", image: "images/items/gilded_blackstone.png" },
    "minecraft:golden_apple": { name: "Golden Apple", image: "images/items/golden_apple.png" },
    "minecraft:cauldron": { name: "Cauldron", image: "images/items/cauldron.png" },
    "minecraft:lead": { name: "Lead", image: "images/items/lead.png" },
    "minecraft:saddle": { name: "Saddle", image: "images/items/saddle.png" },
    "minecraft:diamond_horse_armor": { name: "Diamond Horse Armor", image: "images/items/diamond_horse_armor.png" },
    "minecraft:phantom_membrane": { name: "Phantom Membrane", image: "images/items/phantom_membrane.png" },

    // --- Entity "Items" (Spawn Eggs) ---
    "minecraft:bat_spawn_egg": { name: "Bat", image: "images/items/bat_spawn_egg.png" },
    "minecraft:bee_spawn_egg": { name: "Bee", image: "images/items/bee_spawn_egg.png" },
    "minecraft:chicken_spawn_egg": { name: "Chicken", image: "images/items/chicken_spawn_egg.png" },
    "minecraft:cow_spawn_egg": { name: "Cow", image: "images/items/cow_spawn_egg.png" },
    "minecraft:creeper_spawn_egg": { name: "Creeper", image: "images/items/creeper_spawn_egg.png" },
    "minecraft:pig_spawn_egg": { name: "Pig", image: "images/items/pig_spawn_egg.png" },
    "minecraft:rabbit_spawn_egg": { name: "Rabbit", image: "images/items/rabbit_spawn_egg.png" },
    "minecraft:sheep_spawn_egg": { name: "Sheep", image: "images/items/sheep_spawn_egg.png" },
    "minecraft:skeleton_spawn_egg": { name: "Skeleton", image: "images/items/skeleton_spawn_egg.png" },
    "minecraft:spider_spawn_egg": { name: "Spider", image: "images/items/spider_spawn_egg.png" },
    "minecraft:squid_spawn_egg": { name: "Squid", image: "images/items/squid_spawn_egg.png" },
    "minecraft:witch_spawn_egg": { name: "Witch", image: "images/items/witch_spawn_egg.png" },
    "minecraft:wolf_spawn_egg": { name: "Wolf", image: "images/items/wolf_spawn_egg.png" },
    "minecraft:zombie_spawn_egg": { name: "Zombie", image: "images/items/zombie_spawn_egg.png" },
    "minecraft:blaze_spawn_egg": { name: "Blaze", image: "images/items/blaze_spawn_egg.png" },
    "minecraft:cave_spider_spawn_egg": { name: "Cave Spider", image: "images/items/cave_spider_spawn_egg.png" },
    "minecraft:donkey_spawn_egg": { name: "Donkey", image: "images/items/donkey_spawn_egg.png" },
    "minecraft:glow_squid_spawn_egg": { name: "Glow Squid", image: "images/items/glow_squid_spawn_egg.png" },
    "minecraft:husk_spawn_egg": { name: "Husk", image: "images/items/husk_spawn_egg.png" },
    "minecraft:iron_golem_spawn_egg": { name: "Iron Golem", image: "images/items/iron_golem_spawn_egg.png" },
    "minecraft:magma_cube_spawn_egg": { name: "Magma Cube", image: "images/items/magma_cube_spawn_egg.png" },
    "minecraft:ocelot_spawn_egg": { name: "Ocelot", image: "images/items/ocelot_spawn_egg.png" },
    "minecraft:piglin_spawn_egg": { name: "Piglin", image: "images/items/piglin_spawn_egg.png" },
    "minecraft:silverfish_spawn_egg": { name: "Silverfish", image: "images/items/silverfish_spawn_egg.png" },
    "minecraft:slime_spawn_egg": { name: "Slime", image: "images/items/slime_spawn_egg.png" },
    "minecraft:stray_spawn_egg": { name: "Stray", image: "images/items/stray_spawn_egg.png" },
    "minecraft:strider_spawn_egg": { name: "Strider", image: "images/items/strider_spawn_egg.png" },
    "minecraft:turtle_spawn_egg": { name: "Turtle", image: "images/items/turtle_spawn_egg.png" },
    "minecraft:zombie_horse_spawn_egg": { name: "Zombie Horse", image: "images/items/zombie_horse_spawn_egg.png" },
    "minecraft:allay_spawn_egg": { name: "Allay", image: "images/items/allay_spawn_egg.png" },
    "minecraft:camel_spawn_egg": { name: "Camel", image: "images/items/camel_spawn_egg.png" },
    "minecraft:cat_spawn_egg": { name: "Cat", image: "images/items/cat_spawn_egg.png" },
    "minecraft:dolphin_spawn_egg": { name: "Dolphin", image: "images/items/dolphin_spawn_egg.png" },
    "minecraft:enderman_spawn_egg": { name: "Enderman", image: "images/items/enderman_spawn_egg.png" },
    "minecraft:endermite_spawn_egg": { name: "Endermite", image: "images/items/endermite_spawn_egg.png" },
    "minecraft:fox_spawn_egg": { name: "Fox", image: "images/items/fox_spawn_egg.png" },
    "minecraft:ghast_spawn_egg": { name: "Ghast", image: "images/items/ghast_spawn_egg.png" },
    "minecraft:goat_spawn_egg": { name: "Goat", image: "images/items/goat_spawn_egg.png" },
    "minecraft:guardian_spawn_egg": { name: "Guardian", image: "images/items/guardian_spawn_egg.png" },
    "minecraft:hoglin_spawn_egg": { name: "Hoglin", image: "images/items/hoglin_spawn_egg.png" },
    "minecraft:illusioner_spawn_egg": { name: "Illusioner", image: "images/items/illusioner_spawn_egg.png" },
    "minecraft:llama_spawn_egg": { name: "Llama", image: "images/items/llama_spawn_egg.png" },
    "minecraft:parrot_spawn_egg": { name: "Parrot", image: "images/items/parrot_spawn_egg.png" },
    "minecraft:phantom_spawn_egg": { name: "Phantom", image: "images/items/phantom_spawn_egg.png" },
    "minecraft:pillager_spawn_egg": { name: "Pillager", image: "images/items/pillager_spawn_egg.png" },
    "minecraft:polar_bear_spawn_egg": { name: "Polar Bear", image: "images/items/polar_bear_spawn_egg.png" },
    "minecraft:villager_spawn_egg": { name: "Villager", image: "images/items/villager_spawn_egg.png" },
    "minecraft:wither_skeleton_spawn_egg": { name: "Wither Skeleton", image: "images/items/wither_skeleton_spawn_egg.png" },
    "minecraft:zombie_villager_spawn_egg": { name: "Zombie Villager", image: "images/items/zombie_villager_spawn_egg.png" },
    "minecraft:axolotl_spawn_egg": { name: "Axolotl", image: "images/items/axolotl_spawn_egg.png" },
    "minecraft:evoker_spawn_egg": { name: "Evoker", image: "images/items/evoker_spawn_egg.png" },
    "minecraft:mooshroom_spawn_egg": { name: "Mooshroom", image: "images/items/mooshroom_spawn_egg.png" },
    "minecraft:ravager_spawn_egg": { name: "Ravager", image: "images/items/ravager_spawn_egg.png" },
    "minecraft:shulker_spawn_egg": { name: "Shulker", image: "images/items/shulker_spawn_egg.png" },
    "minecraft:skeleton_horse_spawn_egg": { name: "Skeleton Horse", image: "images/items/skeleton_horse_spawn_egg.png" },
    "minecraft:sniffer_spawn_egg": { name: "Sniffer", image: "images/items/sniffer_spawn_egg.png" },
    "minecraft:elder_guardian_spawn_egg": { name: "Elder Guardian", image: "images/items/elder_guardian_spawn_egg.png" },
    "minecraft:ender_dragon_spawn_egg": { name: "Ender Dragon", image: "images/items/ender_dragon_spawn_egg.png" },
    "minecraft:warden_spawn_egg": { name: "Warden", image: "images/items/warden_spawn_egg.png" },
    "minecraft:wither_spawn_egg": { name: "Wither", image: "images/items/wither_spawn_egg.png" },
};